import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UIProvider, WalletProvider } from 'src/providers'
import ReduxProvider from 'src/providers/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><WalletProvider><ReduxProvider><UIProvider>{children}</UIProvider></ReduxProvider></WalletProvider></body>
    </html>
  )
}
